version: 0.2

env:
  variables:
    CNJ_ARTIFACT_ID: cnj-cloudtrain-loadtest
  parameter-store:
    CLOUDTRAIN_EKS_DEPLOY_ENABLED: "CLOUDTRAIN_CODEBUILD_EKS_DEPLOY_ENABLED"
    CLOUDTRAIN_EKS_CLUSTER_NAME: "CLOUDTRAIN_CODEBUILD_EKS_CLUSTER_NAME"
    CLOUDTRAIN_EKS_INGRESS_HOST: "CLOUDTRAIN_CODEBUILD_EKS_INGRESS_HOST"
    CLOUDTRAIN_EKS_NAMESPACE: "CLOUDTRAIN_CODEBUILD_EKS_NAMESPACE"
    CLOUDTRAIN_EKS_CLUSTER_ROUTE: "CLOUDTRAIN_CODEBUILD_EKS_CLUSTER_ROUTE"
    CLOUDTRAIN_CODEBUILD_GIT_TAG_USER: "CLOUDTRAIN_CODEBUILD_GIT_TAG_USER"
    CLOUDTRAIN_CODEBUILD_GIT_TAG_EMAIL: "CLOUDTRAIN_CODEBUILD_GIT_TAG_EMAIL"
    CLOUDTRAIN_CODEBUILD_OWASP_SCAN_SKIPPED: "CLOUDTRAIN_CODEBUILD_OWASP_SCAN_SKIPPED"
  secrets-manager:
    NEXUS_USER: "cloudtrain-codebuild-nexus:user"
    NEXUS_PASSWORD: "cloudtrain-codebuild-nexus:password"
    SONARQUBE_TOKEN: "cloudtrain-codebuild-sonarqube:token"
    GITHUB_TOKEN: "cloudtrain-codebuild-github:msgoat_pat"
    TEST_OIDC_CLIENT_CLIENT_ID: "cloudtrain-codebuild-common-test:test.oidc.client.clientId"
    TEST_OIDC_CLIENT_CLIENT_SECRET: "cloudtrain-codebuild-common-test:test.oidc.client.clientSecret"
    TEST_OIDC_CLIENT_ACCESS_TOKEN_URI: "cloudtrain-codebuild-common-test:test.oidc.client.accessTokenUri"
    TEST_OIDC_CLIENT_USER: "cloudtrain-codebuild-common-test:test.oidc.client.user"
    TEST_OIDC_CLIENT_PASSWORD: "cloudtrain-codebuild-common-test:test.oidc.client.password"
    NIST_NVD_API_KEY: "cloudtrain-codebuild-nvd-api-key:apiKey"

phases:
  install:
    on-failure: ABORT
    commands:
      - echo "Running phase install"
      - echo "Download and run common installation script"
      - aws s3 cp s3://s3-eu-west-1-cloudtrain-codebuild-shared/cloudtrain-codebuild-install.sh ~/
      - chmod u+x ~/cloudtrain-codebuild-install.sh
      - ~/cloudtrain-codebuild-install.sh
      - echo "Install JDK 21"
      - yum install -y java-21-amazon-corretto-headless
      - export JAVA_HOME=/usr/lib/jvm/java-21-amazon-corretto.x86_64
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Running phase pre_build"
      - echo "Download common configuration files"
      - aws s3 cp s3://s3-eu-west-1-cloudtrain-codebuild-shared/.mvn/settings.xml /root/.m2/settings.xml
  build:
    on-failure: ABORT
    commands:
      - echo "Running phase build"
      - export BRANCH=main
      - export GIT_BRANCH=${CODEBUILD_WEBHOOK_HEAD_REF:11}
      - export VERSION_REVISION=$(grep -m 1 '<revision>' pom.xml | cut -d '<' -f2  | cut -d '>' -f2)
      - export VERSION_CHANGELIST=${GIT_BRANCH:-main}
      - export VERSION_SHA1=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}
      - export PROJECT_VERSION=$VERSION_REVISION.$VERSION_CHANGELIST.$VERSION_SHA1
      - echo "Running Gatling simulations version [$PROJECT_VERSION]"
      - mvn clean verify -f pom.xml -B -ff -e -V -U -P commit-stage -Dchangelist=.$VERSION_CHANGELIST -Dsha1=.$VERSION_SHA1 -Dsonar.token=$SONARQUBE_TOKEN -Ddependency-check.skip=$CLOUDTRAIN_CODEBUILD_OWASP_SCAN_SKIPPED
  post_build:
    commands:
      - echo "Running phase post_build"

cache:
  paths:
    - "/root/.m2/**/*"
    - "/root/.sonar/cache/**/*"